compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 2
mixed_precision: bf16
fsdp_config:
  sharding_strategy: FULL_SHARD
  auto_wrap_policy: transformers.auto_wrap
# cpu_offload: true  # optional
